### ISSUE TITLE
v2.5.0 throws Super expression must either be null or a function

### ISSUE THREAD

**Issue by newsiberian** [lancedikson/bowser#335]
It throws in **production** (development works as expected) at linux chromium, windows chrome (latest

![Screenshot_20190717_160533](https://user-images.githubusercontent.com/11130487/61362792-fd5bbd80-a8ac-11e9-8fef-1b52f2b627ff.png)

Here is how we use it:
```js
import bowser from 'bowser';

export default function() {
  const ua = navigator.userAgent;
  const browser = bowser.getParser(ua);
  let flag;

  if (browser.satisfies({ chrome: '>=0', chromium: '>=0' })) flag = 'chrome';
  else if (browser.satisfies({ firefox: '>=0' })) flag = 'firefox';
  else if (browser.satisfies({ safari: '>=0' })) flag = 'safari';
  else if (browser.satisfies({ opera: '>=0' })) flag = 'opera';
  else if (browser.satisfies({ 'microsoft edge': '>=0' })) flag = 'edge';
  else flag = 'unknown';

  return {
    flag,
    name: browser.getBrowserName(),
    version: browser.getBrowserVersion(),
  };
}
```

**Comment by lancedikson** [comment]
Wow, that's weird. May it be so, that your `production`-building stage is somehow affecting the bowser code? I'd recommend first switching back to `2.4.0` for the production. We should try to reproduce it in repl.it or somewhere else.
What is the exact `ua` at that moment? Is it valid? Just to make sure that the reason is in the code, not in the arguments.

**Comment by newsiberian** [comment]
Mine is `"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"`, but the same happens in FF and Windows Chrome

**Comment by eimanip** [comment]
Same here, using it in an Angular 8 project.

**Comment by newsiberian** [comment]
`mediasoup-client` has `bowser` as dependency and it use it like `"^2.4.0"`.
Temporary fix for guys, who use it:
```
"resolutions": {   
  "mediasoup-client/bowser": "2.4.0"
},
```

**Comment by lancedikson** [comment]
Ok, I'm preparing the patch version with a fix reverting that Error class. 2.5.1 will be ready in a few minutes.

**Comment by lancedikson** [comment]
It's available as 2.5.1. Try it out, please. It should fix the bug.

**Comment by newsiberian** [comment]
@lancedikson? after update to 2.5.1 I now receive `bowser.getParser is not a function` is that ok?

**Comment by lancedikson** [comment]
No, it's not. Thanks for the heads-up. Fixed it as 2.5.2. Now should be fine.

**Comment by lancedikson** [comment]
Long story short: we were trying to reduce the build size and I changed the modules system that Babel uses for the build from `umd` to `auto` and we hadn't had tests for it (but actually should have). So, it broke the build. Now I switched from `auto` to `cjs`, which works and still a bit less, than `umd` option.
